# Generated by Django 3.2.5 on 2021-07-24 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musipedia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='featued_artists',
            new_name='featured_artists',
        ),
    ]
