# Generated by Django 3.2.5 on 2021-07-25 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musipedia', '0002_rename_featued_artists_album_featured_artists'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
