# Generated by Django 3.2.5 on 2021-07-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musipedia', '0006_artist_last_edit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='last_edit',
        ),
    ]
